[package]
name = "record"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structuralize = { git = "https://www.github.com/verdex/structuralize", version = "0.10.0", tag = "release-0.10.0" }